/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package template

import (
	"context"
	"fmt"

	svcapi "github.com/aws/aws-sdk-go/service/ses"
	svcsdk "github.com/aws/aws-sdk-go/service/ses"
	svcsdkapi "github.com/aws/aws-sdk-go/service/ses/sesiface"
	"github.com/google/go-cmp/cmp"
	"github.com/pkg/errors"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"

	svcapitypes "github.com/crossplane/provider-aws/apis/ses/v1alpha1"
	awsclient "github.com/crossplane/provider-aws/pkg/clients"
)

const (
	errUnexpectedObject = "managed resource is not an Template resource"

	errCreateSession = "cannot create a new session"
	errCreate        = "cannot create Template in AWS"
	errUpdate        = "cannot update Template in AWS"
	errDescribe      = "failed to describe Template"
	errDelete        = "failed to delete Template"
)

type connector struct {
	kube client.Client
	opts []option
}

func (c *connector) Connect(ctx context.Context, mg cpresource.Managed) (managed.ExternalClient, error) {
	fmt.Println("============================CONNECT START============================")
	cr, ok := mg.(*svcapitypes.Template)
	if !ok {
		fmt.Println("============================CONNECT END ONE============================")
		return nil, errors.New(errUnexpectedObject)
	}
	sess, err := awsclient.GetConfigV1(ctx, c.kube, mg, cr.Spec.ForProvider.Region)
	if err != nil {
		fmt.Println("============================CONNECT END TWO============================")
		return nil, errors.Wrap(err, errCreateSession)
	}
	fmt.Println("============================CONNECT END THREE============================")
	return newExternal(c.kube, svcapi.New(sess), c.opts), nil
}

func (e *external) Observe(ctx context.Context, mg cpresource.Managed) (managed.ExternalObservation, error) {
	fmt.Println("***************************OBSERVE START***************************")
	cr, ok := mg.(*svcapitypes.Template)
	if !ok {
		fmt.Println("***************************OBSERVE END ONE***************************")
		return managed.ExternalObservation{}, errors.New(errUnexpectedObject)
	}
	if meta.GetExternalName(cr) == "" {
		fmt.Println("***************************OBSERVE END TWO***************************")
		return managed.ExternalObservation{
			ResourceExists: false,
		}, nil
	}
	input := GenerateGetTemplateInput(cr)
	fmt.Println("******************")
	fmt.Println("input: ", input)
	// fmt.Println("input.TemplateName: ", input.TemplateName)
	fmt.Println("******************")
	if err := e.preObserve(ctx, cr, input); err != nil {
		fmt.Println("***************************OBSERVE END THREE***************************")
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	fmt.Println("--------AFTER------------")
	fmt.Println("input: ", input)
	fmt.Println("--------------------")
	resp, err := e.client.GetTemplateWithContext(ctx, input)
	if err != nil {
		fmt.Println("***************************OBSERVE END FOUR***************************")
		return managed.ExternalObservation{ResourceExists: false}, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		fmt.Println("***************************OBSERVE END FIVE***************************")
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	GenerateTemplate(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)

	upToDate, err := e.isUpToDate(cr, resp)
	if err != nil {
		fmt.Println("***************************OBSERVE END SIX***************************")
		return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
	}
	fmt.Println("***************************OBSERVE END LAST***************************")
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:          true,
		ResourceUpToDate:        upToDate,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
}

func (e *external) Create(ctx context.Context, mg cpresource.Managed) (managed.ExternalCreation, error) {
	fmt.Println("################################CREATE START################################")
	cr, ok := mg.(*svcapitypes.Template)
	if !ok {
		fmt.Println("################################CREATE END ONE################################")
		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Creating())
	input := GenerateCreateTemplateInput(cr)
	if err := e.preCreate(ctx, cr, input); err != nil {
		fmt.Println("################################CREATE END TWO################################")
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.CreateTemplateWithContext(ctx, input)
	if err != nil {
		fmt.Println("################################CREATE END THREE################################")
		return managed.ExternalCreation{}, awsclient.Wrap(err, errCreate)
	}
	fmt.Println("################################CREATE END LAST################################")
	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, mg cpresource.Managed) (managed.ExternalUpdate, error) {
	fmt.Println("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^UPDATE START^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
	cr, ok := mg.(*svcapitypes.Template)
	if !ok {
		fmt.Println("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^UPDATE END ONE^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
		return managed.ExternalUpdate{}, errors.New(errUnexpectedObject)
	}
	input := GenerateUpdateTemplateInput(cr)
	fmt.Println("^^^^^^^^^^^")
	fmt.Println("input: ", input)
	fmt.Println("^^^^^^^^^^^")
	if err := e.preUpdate(ctx, cr, input); err != nil {
		fmt.Println("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^UPDATE END TWO^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
		return managed.ExternalUpdate{}, errors.Wrap(err, "pre-update failed")
	}
	resp, err := e.client.UpdateTemplateWithContext(ctx, input)
	fmt.Println("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^UPDATE END LAST^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
	return e.postUpdate(ctx, cr, resp, managed.ExternalUpdate{}, awsclient.Wrap(err, errUpdate))
}

func (e *external) Delete(ctx context.Context, mg cpresource.Managed) error {
	fmt.Println("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$DELETE START$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
	cr, ok := mg.(*svcapitypes.Template)
	if !ok {
		fmt.Println("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$DELETE END ONE$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
		return errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Deleting())
	input := GenerateDeleteTemplateInput(cr)
	ignore, err := e.preDelete(ctx, cr, input)
	if err != nil {
		fmt.Println("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$DELETE END TWO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
		return errors.Wrap(err, "pre-delete failed")
	}
	if ignore {
		fmt.Println("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$DELETE END THREE$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
		return nil
	}
	resp, err := e.client.DeleteTemplateWithContext(ctx, input)
	fmt.Println("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$DELETE END LAST$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
	return e.postDelete(ctx, cr, resp, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDelete))
}

type option func(*external)

func newExternal(kube client.Client, client svcsdkapi.SESAPI, opts []option) *external {
	e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		preDelete:      nopPreDelete,
		postDelete:     nopPostDelete,
		preUpdate:      nopPreUpdate,
		postUpdate:     nopPostUpdate,
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube           client.Client
	client         svcsdkapi.SESAPI
	preObserve     func(context.Context, *svcapitypes.Template, *svcsdk.GetTemplateInput) error
	postObserve    func(context.Context, *svcapitypes.Template, *svcsdk.GetTemplateOutput, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	lateInitialize func(*svcapitypes.TemplateParameters, *svcsdk.GetTemplateOutput) error
	isUpToDate     func(*svcapitypes.Template, *svcsdk.GetTemplateOutput) (bool, error)
	preCreate      func(context.Context, *svcapitypes.Template, *svcsdk.CreateTemplateInput) error
	postCreate     func(context.Context, *svcapitypes.Template, *svcsdk.CreateTemplateOutput, managed.ExternalCreation, error) (managed.ExternalCreation, error)
	preDelete      func(context.Context, *svcapitypes.Template, *svcsdk.DeleteTemplateInput) (bool, error)
	postDelete     func(context.Context, *svcapitypes.Template, *svcsdk.DeleteTemplateOutput, error) error
	preUpdate      func(context.Context, *svcapitypes.Template, *svcsdk.UpdateTemplateInput) error
	postUpdate     func(context.Context, *svcapitypes.Template, *svcsdk.UpdateTemplateOutput, managed.ExternalUpdate, error) (managed.ExternalUpdate, error)
}

func nopPreObserve(context.Context, *svcapitypes.Template, *svcsdk.GetTemplateInput) error {
	fmt.Println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --nopPreObserve-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
	return nil
}

func nopPostObserve(_ context.Context, _ *svcapitypes.Template, _ *svcsdk.GetTemplateOutput, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	fmt.Println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --nopPostObserve-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
	return obs, err
}
func nopLateInitialize(*svcapitypes.TemplateParameters, *svcsdk.GetTemplateOutput) error {
	fmt.Println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --nopLateInitialize-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
	return nil
}
func alwaysUpToDate(*svcapitypes.Template, *svcsdk.GetTemplateOutput) (bool, error) {
	fmt.Println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --alwaysUpToDate-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
	return true, nil
}

func nopPreCreate(context.Context, *svcapitypes.Template, *svcsdk.CreateTemplateInput) error {
	fmt.Println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --nopPreCreate-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
	return nil
}
func nopPostCreate(_ context.Context, _ *svcapitypes.Template, _ *svcsdk.CreateTemplateOutput, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	fmt.Println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --nopPostCreate-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
	return cre, err
}
func nopPreDelete(context.Context, *svcapitypes.Template, *svcsdk.DeleteTemplateInput) (bool, error) {
	fmt.Println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --nopPreDelete-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
	return false, nil
}
func nopPostDelete(_ context.Context, _ *svcapitypes.Template, _ *svcsdk.DeleteTemplateOutput, err error) error {
	fmt.Println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --nopPostDelete-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
	return err
}
func nopPreUpdate(context.Context, *svcapitypes.Template, *svcsdk.UpdateTemplateInput) error {
	fmt.Println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --nopPreUpdate-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
	return nil
}
func nopPostUpdate(_ context.Context, _ *svcapitypes.Template, _ *svcsdk.UpdateTemplateOutput, upd managed.ExternalUpdate, err error) (managed.ExternalUpdate, error) {
	fmt.Println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --nopPostUpdate-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
	return upd, err
}
