ignore:
    resource_names:
        - ConfigurationSet
        - ConfigurationSetEventDestination
        - CustomVerificationEmailTemplate
        - ReceiptFilter
        - ReceiptRule
        - ReceiptRuleSet
    resources:
        Template:
            exceptions:
                errors:
                    404:
                        code: TemplateDoesNotExist