ignore:
    resource_names:
        - ConfigurationSetEventDestination
        - CustomVerificationEmailTemplate
        - ReceiptFilter
        - ReceiptRule
        - ReceiptRuleSet 
        - Template