ignore:
    resource_names:
        - ConfigurationSet
        - ConfigurationSetEventDestination
        - CustomVerificationEmailTemplate
        - ReceiptFilter
        - ReceiptRule
        - ReceiptRuleSet