ignore:
    resource_names:
      - HostedZone
      - ResourceRecordSet
      - QueryLoggingConfig
      - TrafficPolicy
      - TrafficPolicyInstance
      - TrafficPolicyVersion
      - HealthCheck
      - DomainRegistration
      - KeySigningKey
      - VPCAssociationAuthorization