/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package reusabledelegationset

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/route53"

	svcapitypes "github.com/crossplane/provider-aws/apis/route53/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateGetReusableDelegationSetInput returns input for read
// operation.
func GenerateGetReusableDelegationSetInput(cr *svcapitypes.ReusableDelegationSet) *svcsdk.GetReusableDelegationSetInput {
	res := &svcsdk.GetReusableDelegationSetInput{}

	return res
}

// GenerateReusableDelegationSet returns the current state in the form of *svcapitypes.ReusableDelegationSet.
func GenerateReusableDelegationSet(resp *svcsdk.GetReusableDelegationSetOutput) *svcapitypes.ReusableDelegationSet {
	cr := &svcapitypes.ReusableDelegationSet{}

	return cr
}

// GenerateCreateReusableDelegationSetInput returns a create input.
func GenerateCreateReusableDelegationSetInput(cr *svcapitypes.ReusableDelegationSet) *svcsdk.CreateReusableDelegationSetInput {
	res := &svcsdk.CreateReusableDelegationSetInput{}

	if cr.Spec.ForProvider.CallerReference != nil {
		res.SetCallerReference(*cr.Spec.ForProvider.CallerReference)
	}
	if cr.Spec.ForProvider.HostedZoneID != nil {
		res.SetHostedZoneId(*cr.Spec.ForProvider.HostedZoneID)
	}

	return res
}

// GenerateDeleteReusableDelegationSetInput returns a deletion input.
func GenerateDeleteReusableDelegationSetInput(cr *svcapitypes.ReusableDelegationSet) *svcsdk.DeleteReusableDelegationSetInput {
	res := &svcsdk.DeleteReusableDelegationSetInput{}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
